# Generated by Django 4.1.2 on 2022-10-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artiste_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Date_Released', models.DateField()),
                ('Likes', models.IntegerField()),
                ('artiste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicapp.artiste_id')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=4000)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicapp.song')),
            ],
        ),
    ]
