# Generated by Django 4.1.3 on 2022-11-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Date_Released',
            new_name='date_released',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicapp.artiste'),
        ),
        migrations.DeleteModel(
            name='artiste_id',
        ),
    ]
